#!/bin/bash

./blCheck  \
            -1                          \
            -b example/example.bld      \
            -r example/dataDir          \
            -u example/uDir             \
            $@
