#!/bin/bash

./bl_srcgen  \
            -b tmp/junk.bld         \
            -f                      \
            -r tmp/dataDir          \
            -t "a trial title"      \
            -u tmp/uDir             \
            $@
