#!/bin/bash

src/bl_check  \
            -3                           \
            -b example3/example.bld      \
            -d example3/dataDir          \
            -u example3/uDir             \
            $@
