#!/bin/bash

src/bl_check  \
            -2                          \
            -b example2/example.bld      \
            -d example2/dataDir          \
            -u example2/uDir             \
            $@
