#!/bin/bash

./bl_check  \
            -1                          \
            -b example1/example.bld      \
            -d example1/dataDir          \
            -u example1/uDir             \
            $@
