#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/buildList
  
  rm -rf build/* 
  
  pySloc -L py blBootstrap blCheck blListGen blSrcGen  -X cover -X htmlcov -X dist -v $@
else
  echo "DEV_BASE is not defined"
fi
