#!/bin/bash

cd ~ / dev / py / buildlist

rm - rf tmp / *
mkdir - p tmp / dvcz
cp .dvcz / version tmp / dvcz

echo "The build list gets written to tmp/dvcz/lastBuildList."
echo "You may want to add -u tmp/uDir."

. / bl_listgen - b lastBuildList       \
    - D tmp / dvcz                     \
    - k example1 / node / skPriv.pem     \
    - d example1 / dataDir             \
    - L1                             \
    $@
