#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/buildlist
  
  autopep8 -ai -r buildlist bl_bootstrap doListGen doSrcGen bl_check bl_create_test_data1 bl_list_gen bl_src_gen *.py
  echo "not styling example/ subdir"
  echo "not styling example1/ subdir"
  echo "not styling example2/ subdir"
  echo "not styling example3/ subdir"
  
else
  echo "DEV_BASE is not defined"
fi
