#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/buildList
  
  autopep8 -ai -r buildList blBootstrap doListGen doSrcGen blCheck blListGen blSrcGen *.py
  echo "not styling example/ subdir"
  
else
  echo "DEV_BASE is not defined"
fi
