[meta]
version = "0.1.0"

[project]
name = "buildlist"
package = "buildlist"
main_lang = "py"
version = "0.10.7"
version_date = "2018-03-13"
author = "Jim Dixon"
author_email = "jddixon@gmail.com"
description = "digitally signed indented list of content keys"
copyright = "2014-2017"
dev_status = "beta"
license = "mit"
relpath = "py/buildlist"
state = "shared"
url = "https://jddixon.github.io/buildlist"

[py]
packages = [ "buildlist",]
package_dir = [ "src",]
test_dir = "tests"
py_modules = []
scripts = [ "src/bl_check", "src/bl_createtestdata1", "src/bl_listgen", "src/bl_srcgen",]
ext_modules = []
distshare = [ "merkletree", "nlhtree_py", "optionz", "rnglib", "xlattice_py",]
requirements = [ "pycrypt", "scandir", "setuptools",]
test_requirements = [ "pysha3",]
